# Generated by Django 6.1.1 on 2026-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.URLField(blank=True, default='', help_text='X / Twitter profile or page URL.')),
                ('facebook_handle', models.URLField(blank=True, default='', help_text='Facebook page URL.')),
                ('promotion_email', models.EmailField(blank=True, default='', help_text='For partnership / advertising inquiries.', max_length=254)),
                ('tech_expert_email', models.EmailField(blank=True, default='', help_text='For reporting glitches / bugs in the system.', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', help_text='For customer / usage problems, not software bugs.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
