# Generated by Django 6.1.1 on 2026-09-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='customer_support_mobile',
            field=models.CharField(blank=True, default='', help_text='Customer support phone / WhatsApp number shown to readers.', max_length=32),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_channel',
            field=models.URLField(blank=True, default='', help_text='WhatsApp channel invite / URL.'),
        ),
    ]
