# Generated by Django 6.1.1 on 2026-09-20 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0007_authorfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorfollow',
            options={},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
