# Generated by Django 6.1.1 on 2026-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0008_alter_authorfollow_options_alter_staffprofile_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='get_blog_notification',
            field=models.BooleanField(default=True, help_text='WETHER TO BEEP THE STAFF WHEN THEIR BLOG GET VIEWWED'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='last_promotion',
            field=models.DateField(blank=True, help_text='DIFFERENT FROM THEN THEY CREATED ACCOUNT, THIS CAN BE USED TO SHOW THEY HAVE BEEN PROMOTED WITHING A TIME SPA', null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='speciality',
            field=models.JSONField(blank=True, default=list, help_text='CSV. IF THE STAFF HAVE A SPECIAL NICHE ABOUT POST THEY LOVE MAKING', null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='tribute_bio',
            field=models.TextField(blank=True, help_text='DIFFERENT FROM BIO AS THIS ONE, THE ADMINS WRITE IT FOR THE STAFF', null=True),
        ),
    ]
