# Generated by Django 6.1.1 on 2026-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0009_alter_staffprofile_get_blog_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
