# Generated by Django 6.1.1 on 2026-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0011_backfill_staffprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('FOUNDER', 'Founder'), ('SNR-JOURNALIST', 'Snr-Journalist'), ('JOURNALIST', 'Journalist')], default='JOURNALIST', max_length=20),
        ),
    ]
