# Generated by Django 6.1.1 on 2026-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0007_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('UNIVERSITY', 'UNIVERSITY'), ('POLYTECHNIC', 'POLYTECHNIC'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('POSTUTME', 'POSTUTME'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('TECHNOLOGY', 'TECHNOLOGY'), ('SECURITY', 'SECURITY'), ('NIGERIA-POLITICS', 'NIGERIA-POLITICS'), ('GENERAL', 'GENERAL')], max_length=20),
        ),
    ]
