# Generated by Django 6.1.1 on 2026-09-23 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0008_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='CHANGES ANYTIME UPDATES IS MADE', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('UNIVERSITY', 'UNIVERSITY'), ('POLYTECHNIC', 'POLYTECHNIC'), ('ORGANIZATION', 'ORGANIZATION'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('POSTUTME', 'POSTUTME'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('TECHNOLOGY', 'TECHNOLOGY'), ('SECURITY', 'SECURITY'), ('GENERAL', 'GENERAL')], max_length=20),
        ),
    ]
