# Generated by Django 6.1.1 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0011_backfill_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
