# Generated by Django 6.1.1 on 2026-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0013_blog_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('UNIVERSITY', 'UNIVERSITY'), ('POLYTECHNIC', 'POLYTECHNIC'), ('ORGANIZATION', 'ORGANIZATION'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NECO', 'NECO'), ('POSTUTME', 'POSTUTME'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('TECHNOLOGY', 'TECHNOLOGY'), ('GENERAL', 'GENERAL')], max_length=20),
        ),
    ]
