# Generated by Django 6.1.1 on 2026-09-25 21:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt', models.CharField(help_text='Short description shown under the picture.', max_length=150)),
                ('quality', models.CharField(choices=[('low', 'Low - smallest file, fastest load'), ('medium', 'Medium - balanced'), ('high', 'High - best detail, largest file')], default='medium', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('url'), django.db.models.functions.text.Lower('alt'), name='unique_archive_image_url_alt')],
            },
        ),
    ]
