# Generated by Django 6.1.1 on 2026-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCHIVE', '0003_archiveimage_file_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveimage',
            name='alt',
            field=models.CharField(help_text='Short description shown under the picture/file.', max_length=150),
        ),
    ]
