# Generated by Django 6.1.1 on 2026-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverttext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adverttext',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
