# Generated by Django 6.1.1 on 2026-10-09 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0002_adverttext_is_active_adverttext_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('heading', models.CharField(blank=True, default='', max_length=90)),
                ('body', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
